server:
    port: 8080
frontend:
    port: 3000
jmeter:
    path: jmeter
    master_hostname: 192.168.4.74
    agent_csv_data_dir: /opt/jmeter/csv-data
slave:
    heartbeat_interval: 30
dirs:
    data: ./data
    uploads: ./uploads
    results: ./results
